rsync -a hconf/hadoop-env.sh /usr/hadoop/etc/hadoop/hadoop-env.sh 
rsync -a hconf/mapred-site.xml /usr/hadoop/etc/hadoop/mapred-site.xml
rsync -a hconf/core-site.xml /usr/hadoop/etc/hadoop/core-site.xml
rsync -a hconf/yarn-site.xml /usr/hadoop/etc/hadoop/yarn-site.xml
rsync -a hconf/hdfs-site.xml /usr/hadoop/etc/hadoop/hdfs-site.xml
rsync -a hconf/slaves /usr/hadoop/etc/hadoop/slaves
rsync -a hconf/masters /usr/hadoop/etc/hadoop/masters
rsync -a hbconf/hbase-env.sh /usr/hadoop/hbase/conf/hbase-env.sh
rsync -a hbconf/hbase-site.xml /usr/hadoop/hbase/conf/hbase-site.xml
rsync -a hbconf/regionservers /usr/hadoop/hbase/conf/regionservers
rsync -a hbconf/start-hbase.sh /usr/hadoop/hbase/bin/start-hbase.sh
