rsync -a hconf/hadoop-env.sh /usr/hadoop/etc/hadoop/hadoop-env.sh 
rsync -a hconf/pseudo/mapred-site.xml /usr/hadoop/etc/hadoop/mapred-site.xml
rsync -a hconf/pseudo/core-site.xml /usr/hadoop/etc/hadoop/core-site.xml
rsync -a hconf/pseudo/yarn-site.xml /usr/hadoop/etc/hadoop/yarn-site.xml
rsync -a hconf/pseudo/hdfs-site.xml /usr/hadoop/etc/hadoop/hdfs-site.xml
rsync -a hconf/pseudo/slaves /usr/hadoop/etc/hadoop/slaves
rsync -a hconf/pseudo/masters /usr/hadoop/etc/hadoop/masters
rsync -a hbconf/hbase-env.sh /usr/hadoop/hbase/conf/hbase-env.sh
rsync -a hbconf/pseudo/hbase-site.xml /usr/hadoop/hbase/conf/hbase-site.xml
rsync -a hbconf/pseudo/regionservers /usr/hadoop/hbase/conf/regionservers
rsync -a hbconf/pseudo/start-hbase.sh /usr/hadoop/hbase/bin/start-hbase.sh
